### ISSUE TITLE
Support for Python 3.9, 3.10, ...?

### ISSUE THREAD

**Issue by mat-l** [flask-dashboard/Flask-MonitoringDashboard#428]
**Describe the bug**

**To Reproduce**
1. Install Flask-MonitoringDashboard in python:3.9.10-alpine3.14 

**Expected behavior**
Successfull installation

**Desktop (please complete the following information):**
 - Docker
 - 
**Additional context**
failed to solve: process "/bin/sh -c python -m pip install git+https://github.com/flask-dashboard/Flask-MonitoringDashboard.git" did not complete successfully: exit code: 1
$ docker compose up --build
WARN[0000] network default: network.external.name is deprecated. Please set network.name with external: true 
[+] Building 91.6s (10/11)                                                                                        
 => [internal] load .dockerignore                                                                            0.0s
 => => transferring context: 2B                                                                              0.0s
 => [internal] load build definition from Dockerfile                                                         0.0s
 => => transferring dockerfile: 528B                                                                         0.0s
 => [internal] load metadata for docker.io/library/python:3.9.10-alpine3.14                                  0.8s
 => [internal] load build context                                                                            0.1s
 => => transferring context: 64.91kB                                                                         0.0s
 => CACHED [1/7] FROM docker.io/library/python:3.9.10-alpine3.14@sha256:e995c2bfb3e6466d86ceec64a728b9d226a  0.0s
 => [2/7] RUN apk update && apk upgrade &&     apk add --no-cache git                                        9.9s
 => [3/7] WORKDIR /srv                                                                                       0.1s
 => [4/7] RUN pip install --upgrade pip                                                                      6.9s 
 => [5/7] RUN pip install flask gunicorn Flask-BasicAuth                                                     4.4s 
 => ERROR [6/7] RUN python -m pip install git+https://github.com/flask-dashboard/Flask-MonitoringDashboard  69.5s 
------                                                                                                            
 > [6/7] RUN python -m pip install git+https://github.com/flask-dashboard/Flask-MonitoringDashboard.git:          
#0 0.661 Collecting git+https://github.com/flask-dashboard/Flask-MonitoringDashboard.git
#0 0.662   Cloning https://github.com/flask-dashboard/Flask-MonitoringDashboard.git to /tmp/pip-req-build-_k4aeh5h
#0 0.666   Running command git clone --filter=blob:none --quiet https://github.com/flask-dashboard/Flask-MonitoringDashboard.git /tmp/pip-req-build-_k4aeh5h
#0 5.455   Resolved https://github.com/flask-dashboard/Flask-MonitoringDashboard.git to commit 7630227e9f961584a7b61d1f7c237789bcaced59
#0 5.461   Preparing metadata (setup.py): started
#0 9.924   Preparing metadata (setup.py): finished with status 'done'
#0 9.937 Requirement already satisfied: click in /usr/local/lib/python3.9/site-packages (from Flask-MonitoringDashboard==3.1.1) (8.1.3)
#0 10.18 Collecting apscheduler (from Flask-MonitoringDashboard==3.1.1)
#0 10.34   Downloading APScheduler-3.10.1-py3-none-any.whl (59 kB)
#0 10.42      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 59.2/59.2 kB 719.6 kB/s eta 0:00:00
#0 10.42 Requirement already satisfied: flask>=0.9 in /usr/local/lib/python3.9/site-packages (from Flask-MonitoringDashboard==3.1.1) (2.2.3)
#0 10.99 Collecting sqlalchemy>=1.1.9 (from Flask-MonitoringDashboard==3.1.1)
#0 11.02   Downloading SQLAlchemy-2.0.9-cp39-cp39-musllinux_1_1_x86_64.whl (2.8 MB)
#0 12.42      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.8/2.8 MB 2.0 MB/s eta 0:00:00
#0 12.50 Collecting configparser (from Flask-MonitoringDashboard==3.1.1)
#0 12.62   Downloading configparser-5.3.0-py3-none-any.whl (19 kB)
#0 12.98 Collecting psutil (from Flask-MonitoringDashboard==3.1.1)
#0 13.01   Downloading psutil-5.9.5.tar.gz (493 kB)
#0 13.18      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 493.5/493.5 kB 2.9 MB/s eta 0:00:00
#0 13.31   Installing build dependencies: started
#0 16.30   Installing build dependencies: finished with status 'done'
#0 16.30   Getting requirements to build wheel: started
#0 16.61   Getting requirements to build wheel: finished with status 'done'
#0 16.62   Preparing metadata (pyproject.toml): started
#0 16.93   Preparing metadata (pyproject.toml): finished with status 'done'
#0 16.99 Collecting colorhash (from Flask-MonitoringDashboard==3.1.1)
#0 17.03   Downloading colorhash-1.2.1-py3-none-any.whl (5.7 kB)
#0 17.41 Collecting numpy (from Flask-MonitoringDashboard==3.1.1)
#0 17.45   Downloading numpy-1.24.2.tar.gz (10.9 MB)
#0 20.39      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.9/10.9 MB 3.7 MB/s eta 0:00:00
#0 21.51   Installing build dependencies: started
#0 25.97   Installing build dependencies: finished with status 'done'
#0 25.97   Getting requirements to build wheel: started
#0 26.54   Getting requirements to build wheel: finished with status 'done'
#0 26.55   Preparing metadata (pyproject.toml): started
#0 26.96   Preparing metadata (pyproject.toml): finished with status 'done'
#0 27.14 Collecting pytz (from Flask-MonitoringDashboard==3.1.1)
#0 27.17   Downloading pytz-2023.3-py2.py3-none-any.whl (502 kB)
#0 27.30      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 502.3/502.3 kB 4.1 MB/s eta 0:00:00
#0 27.41 Collecting tzlocal==2.0 (from Flask-MonitoringDashboard==3.1.1)
#0 27.45   Downloading tzlocal-2.0.0-py2.py3-none-any.whl (15 kB)
#0 27.74 Collecting scipy (from Flask-MonitoringDashboard==3.1.1)
#0 27.76   Downloading scipy-1.10.1.tar.gz (42.4 MB)
#0 40.11      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.4/42.4 MB 2.9 MB/s eta 0:00:00
#0 46.45   Installing build dependencies: started
#0 68.65   Installing build dependencies: finished with status 'error'
#0 68.68   error: subprocess-exited-with-error
#0 68.68   
#0 68.68   × pip subprocess to install build dependencies did not run successfully.
#0 68.68   │ exit code: 1
#0 68.68   ╰─> [275 lines of output]
#0 68.68       Ignoring numpy: markers 'python_version == "3.8" and platform_machine == "aarch64" and platform_python_implementation != "PyPy"' don't match your environment
#0 68.68       Ignoring numpy: markers 'python_version == "3.8" and platform_machine == "arm64" and platform_system == "Darwin"' don't match your environment
#0 68.68       Ignoring numpy: markers 'python_version == "3.9" and platform_machine == "arm64" and platform_system == "Darwin"' don't match your environment
#0 68.68       Ignoring numpy: markers 'platform_machine == "loongarch64"' don't match your environment
#0 68.68       Ignoring numpy: markers 'python_version == "3.10" and platform_system == "Windows" and platform_python_implementation != "PyPy"' don't match your environment
#0 68.68       Ignoring numpy: markers 'python_version == "3.8" and (platform_machine != "arm64" or platform_system != "Darwin") and platform_machine != "aarch64" and platform_machine != "loongarch64" and platform_python_implementation != "PyPy"' don't match your environment
#0 68.68       Ignoring numpy: markers 'python_version == "3.10" and (platform_system != "Windows" and platform_machine != "loongarch64") and platform_python_implementation != "PyPy"' don't match your environment
#0 68.68       Ignoring numpy: markers 'python_version == "3.11" and platform_python_implementation != "PyPy"' don't match your environment
#0 68.68       Ignoring numpy: markers 'python_version >= "3.12"' don't match your environment
#0 68.68       Ignoring numpy: markers 'python_version >= "3.8" and platform_python_implementation == "PyPy"' don't match your environment
#0 68.68       Collecting meson-python<0.13.0,>=0.11.0
#0 68.68         Downloading meson_python-0.12.1-py3-none-any.whl (66 kB)
#0 68.68            ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 66.2/66.2 kB 732.9 kB/s eta 0:00:00
#0 68.68       Collecting Cython<3.0,>=0.29.32
#0 68.68         Using cached Cython-0.29.34-cp39-cp39-musllinux_1_1_x86_64.whl (2.1 MB)
#0 68.68       Collecting pybind11==2.10.1
#0 68.68         Downloading pybind11-2.10.1-py3-none-any.whl (216 kB)
#0 68.68            ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 216.1/216.1 kB 2.3 MB/s eta 0:00:00
#0 68.68       Collecting pythran<0.13.0,>=0.12.0
#0 68.68         Downloading pythran-0.12.1-py3-none-any.whl (4.2 MB)
#0 68.68            ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 2.3 MB/s eta 0:00:00
#0 68.68       Collecting wheel<0.39.0
#0 68.68         Downloading wheel-0.38.4-py3-none-any.whl (36 kB)
#0 68.68       Collecting numpy==1.19.5
#0 68.68         Downloading numpy-1.19.5.zip (7.3 MB)
#0 68.68            ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.3/7.3 MB 2.0 MB/s eta 0:00:00
#0 68.68         Installing build dependencies: started
#0 68.68         Installing build dependencies: finished with status 'done'
#0 68.68         Getting requirements to build wheel: started
#0 68.68         Getting requirements to build wheel: finished with status 'done'
#0 68.68         Preparing metadata (pyproject.toml): started
#0 68.68         Preparing metadata (pyproject.toml): finished with status 'error'
#0 68.68         error: subprocess-exited-with-error
#0 68.68       
#0 68.68         × Preparing metadata (pyproject.toml) did not run successfully.
#0 68.68         │ exit code: 1
#0 68.68         ╰─> [228 lines of output]
#0 68.68             Running from numpy source directory.
#0 68.68             setup.py:480: UserWarning: Unrecognized setuptools command, proceeding with generating Cython sources and expanding templates
#0 68.68               run_build = parse_setuppy_commands()
#0 68.68             Processing numpy/random/_bounded_integers.pxd.in
#0 68.68             Processing numpy/random/_bounded_integers.pyx.in
#0 68.68             Processing numpy/random/mtrand.pyx
#0 68.68             Processing numpy/random/_generator.pyx
#0 68.68             Processing numpy/random/_sfc64.pyx
#0 68.68             Processing numpy/random/bit_generator.pyx
#0 68.68             Processing numpy/random/_philox.pyx
#0 68.68             Processing numpy/random/_mt19937.pyx
#0 68.68             Processing numpy/random/_pcg64.pyx
#0 68.68             Processing numpy/random/_common.pyx
#0 68.68             Cythonizing sources
#0 68.68             blas_opt_info:
#0 68.68             blas_mkl_info:
#0 68.68             customize UnixCCompiler
#0 68.68               libraries mkl_rt not found in ['/usr/local/lib', '/usr/lib']
#0 68.68               NOT AVAILABLE
#0 68.68       
#0 68.68             blis_info:
#0 68.68               libraries blis not found in ['/usr/local/lib', '/usr/lib']
#0 68.68               NOT AVAILABLE
#0 68.68       
#0 68.68             openblas_info:
#0 68.68               libraries openblas not found in ['/usr/local/lib', '/usr/lib']
#0 68.68               NOT AVAILABLE
#0 68.68       
#0 68.68             atlas_3_10_blas_threads_info:
#0 68.68             Setting PTATLAS=ATLAS
#0 68.68               libraries tatlas not found in ['/usr/local/lib', '/usr/lib']
#0 68.68               NOT AVAILABLE
#0 68.68       
#0 68.68             atlas_3_10_blas_info:
#0 68.68               libraries satlas not found in ['/usr/local/lib', '/usr/lib']
#0 68.68               NOT AVAILABLE
#0 68.68       
#0 68.68             atlas_blas_threads_info:
#0 68.68             Setting PTATLAS=ATLAS
#0 68.68               libraries ptf77blas,ptcblas,atlas not found in ['/usr/local/lib', '/usr/lib']
#0 68.68               NOT AVAILABLE
#0 68.68       
#0 68.68             atlas_blas_info:
#0 68.68               libraries f77blas,cblas,atlas not found in ['/usr/local/lib', '/usr/lib']
#0 68.68               NOT AVAILABLE
#0 68.68       
#0 68.68             accelerate_info:
#0 68.68               NOT AVAILABLE
#0 68.68       
#0 68.68             /tmp/pip-install-03yvatpe/numpy_898aee117c134bcea934e228f7bac285/numpy/distutils/system_info.py:1914: UserWarning:
#0 68.68                 Optimized (vendor) Blas libraries are not found.
#0 68.68                 Falls back to netlib Blas library which has worse performance.
#0 68.68                 A better performance should be easily gained by switching
#0 68.68                 Blas library.
#0 68.68               if self._calc_info(blas):
#0 68.68             blas_info:
#0 68.68               libraries blas not found in ['/usr/local/lib', '/usr/lib']
#0 68.68               NOT AVAILABLE
#0 68.68       
#0 68.68             /tmp/pip-install-03yvatpe/numpy_898aee117c134bcea934e228f7bac285/numpy/distutils/system_info.py:1914: UserWarning:
#0 68.68                 Blas (http://www.netlib.org/blas/) libraries not found.
#0 68.68                 Directories to search for the libraries can be specified in the
#0 68.68                 numpy/distutils/site.cfg file (section [blas]) or by setting
#0 68.68                 the BLAS environment variable.
#0 68.68               if self._calc_info(blas):
#0 68.68             blas_src_info:
#0 68.68               NOT AVAILABLE
#0 68.68       
#0 68.68             /tmp/pip-install-03yvatpe/numpy_898aee117c134bcea934e228f7bac285/numpy/distutils/system_info.py:1914: UserWarning:
#0 68.68                 Blas (http://www.netlib.org/blas/) sources not found.
#0 68.68                 Directories to search for the sources can be specified in the
#0 68.68                 numpy/distutils/site.cfg file (section [blas_src]) or by setting
#0 68.68                 the BLAS_SRC environment variable.
#0 68.68               if self._calc_info(blas):
#0 68.68               NOT AVAILABLE
#0 68.68       
#0 68.68             non-existing path in 'numpy/distutils': 'site.cfg'
#0 68.68             lapack_opt_info:
#0 68.68             lapack_mkl_info:
#0 68.68               libraries mkl_rt not found in ['/usr/local/lib', '/usr/lib']
#0 68.68               NOT AVAILABLE
#0 68.68       
#0 68.68             openblas_lapack_info:
#0 68.68               libraries openblas not found in ['/usr/local/lib', '/usr/lib']
#0 68.68               NOT AVAILABLE
#0 68.68       
#0 68.68             openblas_clapack_info:
#0 68.68               libraries openblas,lapack not found in ['/usr/local/lib', '/usr/lib']
#0 68.68               NOT AVAILABLE
#0 68.68       
#0 68.68             flame_info:
#0 68.68               libraries flame not found in ['/usr/local/lib', '/usr/lib']
#0 68.68               NOT AVAILABLE
#0 68.68       
#0 68.68             atlas_3_10_threads_info:
#0 68.68             Setting PTATLAS=ATLAS
#0 68.68               libraries lapack_atlas not found in /usr/local/lib
#0 68.68               libraries tatlas,tatlas not found in /usr/local/lib
#0 68.68               libraries lapack_atlas not found in /usr/lib
#0 68.68               libraries tatlas,tatlas not found in /usr/lib
#0 68.68             <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
#0 68.68               NOT AVAILABLE
#0 68.68       
#0 68.68             atlas_3_10_info:
#0 68.68               libraries lapack_atlas not found in /usr/local/lib
#0 68.68               libraries satlas,satlas not found in /usr/local/lib
#0 68.68               libraries lapack_atlas not found in /usr/lib
#0 68.68               libraries satlas,satlas not found in /usr/lib
#0 68.68             <class 'numpy.distutils.system_info.atlas_3_10_info'>
#0 68.68               NOT AVAILABLE
#0 68.68       
#0 68.68             atlas_threads_info:
#0 68.68             Setting PTATLAS=ATLAS
#0 68.68               libraries lapack_atlas not found in /usr/local/lib
#0 68.68               libraries ptf77blas,ptcblas,atlas not found in /usr/local/lib
#0 68.68               libraries lapack_atlas not found in /usr/lib
#0 68.68               libraries ptf77blas,ptcblas,atlas not found in /usr/lib
#0 68.68             <class 'numpy.distutils.system_info.atlas_threads_info'>
#0 68.68               NOT AVAILABLE
#0 68.68       
#0 68.68             atlas_info:
#0 68.68               libraries lapack_atlas not found in /usr/local/lib
#0 68.68               libraries f77blas,cblas,atlas not found in /usr/local/lib
#0 68.68               libraries lapack_atlas not found in /usr/lib
#0 68.68               libraries f77blas,cblas,atlas not found in /usr/lib
#0 68.68             <class 'numpy.distutils.system_info.atlas_info'>
#0 68.68               NOT AVAILABLE
#0 68.68       
#0 68.68             lapack_info:
#0 68.68               libraries lapack not found in ['/usr/local/lib', '/usr/lib']
#0 68.68               NOT AVAILABLE
#0 68.68       
#0 68.68             /tmp/pip-install-03yvatpe/numpy_898aee117c134bcea934e228f7bac285/numpy/distutils/system_info.py:1748: UserWarning:
#0 68.68                 Lapack (http://www.netlib.org/lapack/) libraries not found.
#0 68.68                 Directories to search for the libraries can be specified in the
#0 68.68                 numpy/distutils/site.cfg file (section [lapack]) or by setting
#0 68.68                 the LAPACK environment variable.
#0 68.68               return getattr(self, '_calc_info_{}'.format(name))()
#0 68.68             lapack_src_info:
#0 68.68               NOT AVAILABLE
#0 68.68       
#0 68.68             /tmp/pip-install-03yvatpe/numpy_898aee117c134bcea934e228f7bac285/numpy/distutils/system_info.py:1748: UserWarning:
#0 68.68                 Lapack (http://www.netlib.org/lapack/) sources not found.
#0 68.68                 Directories to search for the sources can be specified in the
#0 68.68                 numpy/distutils/site.cfg file (section [lapack_src]) or by setting
#0 68.68                 the LAPACK_SRC environment variable.
#0 68.68               return getattr(self, '_calc_info_{}'.format(name))()
#0 68.68               NOT AVAILABLE
#0 68.68       
#0 68.68             numpy_linalg_lapack_lite:
#0 68.68               FOUND:
#0 68.68                 language = c
#0 68.68                 define_macros = [('HAVE_BLAS_ILP64', None), ('BLAS_SYMBOL_SUFFIX', '64_')]
#0 68.68       
#0 68.68             /usr/local/lib/python3.9/distutils/dist.py:274: UserWarning: Unknown distribution option: 'define_macros'
#0 68.68               warnings.warn(msg)
#0 68.68             running dist_info
#0 68.68             running build_src
#0 68.68             build_src
#0 68.68             building py_modules sources
#0 68.68             creating build
#0 68.68             creating build/src.linux-x86_64-3.9
#0 68.68             creating build/src.linux-x86_64-3.9/numpy
#0 68.68             creating build/src.linux-x86_64-3.9/numpy/distutils
#0 68.68             building library "npymath" sources
#0 68.68             Could not locate executable gfortran
#0 68.68             Could not locate executable f95
#0 68.68             Could not locate executable ifort
#0 68.68             Could not locate executable ifc
#0 68.68             Could not locate executable lf95
#0 68.68             Could not locate executable pgfortran
#0 68.68             Could not locate executable nvfortran
#0 68.68             Could not locate executable f90
#0 68.68             Could not locate executable f77
#0 68.68             Could not locate executable fort
#0 68.68             Could not locate executable efort
#0 68.68             Could not locate executable efc
#0 68.68             Could not locate executable g77
#0 68.68             Could not locate executable g95
#0 68.68             Could not locate executable pathf95
#0 68.68             Could not locate executable nagfor
#0 68.68             don't know how to compile Fortran code on platform 'posix'
#0 68.68             Traceback (most recent call last):
#0 68.68               File "/usr/local/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
#0 68.68                 main()
#0 68.68               File "/usr/local/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
#0 68.68                 json_out['return_val'] = hook(**hook_input['kwargs'])
#0 68.68               File "/usr/local/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 149, in prepare_metadata_for_build_wheel
#0 68.68                 return hook(metadata_directory, config_settings)
#0 68.68               File "/tmp/pip-build-env-jcdmxh0h/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 157, in prepare_metadata_for_build_wheel
#0 68.68                 self.run_setup()
#0 68.68               File "/tmp/pip-build-env-jcdmxh0h/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 248, in run_setup
#0 68.68                 super(_BuildMetaLegacyBackend,
#0 68.68               File "/tmp/pip-build-env-jcdmxh0h/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 142, in run_setup
#0 68.68                 exec(compile(code, __file__, 'exec'), locals())
#0 68.68               File "setup.py", line 508, in <module>
#0 68.68                 setup_package()
#0 68.68               File "setup.py", line 500, in setup_package
#0 68.68                 setup(**metadata)
#0 68.68               File "/tmp/pip-install-03yvatpe/numpy_898aee117c134bcea934e228f7bac285/numpy/distutils/core.py", line 169, in setup
#0 68.68                 return old_setup(**new_attr)
#0 68.68               File "/tmp/pip-build-env-jcdmxh0h/overlay/lib/python3.9/site-packages/setuptools/__init__.py", line 165, in setup
#0 68.68                 return distutils.core.setup(**attrs)
#0 68.68               File "/usr/local/lib/python3.9/distutils/core.py", line 148, in setup
#0 68.68                 dist.run_commands()
#0 68.68               File "/usr/local/lib/python3.9/distutils/dist.py", line 966, in run_commands
#0 68.68                 self.run_command(cmd)
#0 68.68               File "/usr/local/lib/python3.9/distutils/dist.py", line 985, in run_command
#0 68.68                 cmd_obj.run()
#0 68.68               File "/tmp/pip-build-env-jcdmxh0h/overlay/lib/python3.9/site-packages/setuptools/command/dist_info.py", line 31, in run
#0 68.68                 egg_info.run()
#0 68.68               File "/tmp/pip-install-03yvatpe/numpy_898aee117c134bcea934e228f7bac285/numpy/distutils/command/egg_info.py", line 24, in run
#0 68.68                 self.run_command("build_src")
#0 68.68               File "/usr/local/lib/python3.9/distutils/cmd.py", line 313, in run_command
#0 68.68                 self.distribution.run_command(command)
#0 68.68               File "/usr/local/lib/python3.9/distutils/dist.py", line 985, in run_command
#0 68.68                 cmd_obj.run()
#0 68.68               File "/tmp/pip-install-03yvatpe/numpy_898aee117c134bcea934e228f7bac285/numpy/distutils/command/build_src.py", line 144, in run
#0 68.68                 self.build_sources()
#0 68.68               File "/tmp/pip-install-03yvatpe/numpy_898aee117c134bcea934e228f7bac285/numpy/distutils/command/build_src.py", line 155, in build_sources
#0 68.68                 self.build_library_sources(*libname_info)
#0 68.68               File "/tmp/pip-install-03yvatpe/numpy_898aee117c134bcea934e228f7bac285/numpy/distutils/command/build_src.py", line 288, in build_library_sources
#0 68.68                 sources = self.generate_sources(sources, (lib_name, build_info))
#0 68.68               File "/tmp/pip-install-03yvatpe/numpy_898aee117c134bcea934e228f7bac285/numpy/distutils/command/build_src.py", line 378, in generate_sources
#0 68.68                 source = func(extension, build_dir)
#0 68.68               File "numpy/core/setup.py", line 663, in get_mathlib_info
#0 68.68                 raise RuntimeError("Broken toolchain: cannot link a simple C program")
#0 68.68             RuntimeError: Broken toolchain: cannot link a simple C program
#0 68.68             [end of output]
#0 68.68       
#0 68.68         note: This error originates from a subprocess, and is likely not a problem with pip.
#0 68.68       error: metadata-generation-failed
#0 68.68       
#0 68.68       × Encountered error while generating package metadata.
#0 68.68       ╰─> See above for output.
#0 68.68       
#0 68.68       note: This is an issue with the package mentioned above, not pip.
#0 68.68       hint: See above for details.
#0 68.68       [end of output]
#0 68.68   
#0 68.68   note: This error originates from a subprocess, and is likely not a problem with pip.
#0 68.68 error: subprocess-exited-with-error
#0 68.68 
#0 68.68 × pip subprocess to install build dependencies did not run successfully.
#0 68.68 │ exit code: 1
#0 68.68 ╰─> See above for output.
#0 68.68 
#0 68.68 note: This error originates from a subprocess, and is likely not a problem with pip.
------
failed to solve: process "/bin/sh -c python -m pip install git+https://github.com/flask-dashboard/Flask-MonitoringDashboard.git" did not complete successfully: exit code: 1

**Comment by mat-l** [comment]
The last weeks the flask-dashboard was still working in combination with Flask 2.2.2, but it stopped working with Flask 2.3.2:

 File "/home/xxx/PycharmProjects/xxx/app.py", line 27, in <module>
    dashboard.bind(app)
  File "/home/xxx/PycharmProjects/xxx/venv/lib/python3.9/site-packages/flask_monitoringdashboard/__init__.py", line 67, in bind
    blueprint.before_app_first_request(init_measurement)
AttributeError: 'Blueprint' object has no attribute 'before_app_first_request'
[2023-05-03 16:38:00 +0200] [18344] [ERROR] Exception in worker process

Are there any plans to make the dashboard compatible with with the newer Python versions?

**Comment by mircealungu** [comment]
Ehi @mat-l . We're a bit short on people working on FMD at the moment... Is there any chance that you can look into this and send a PR?

**Comment by jakeLester66** [comment]
Hello! I came accross a youtube video presenting this and it looks so cool I wanted to try it out on my web app. However... we are running python 3.10 😭 

Just wanted to check in if there was any plan on upgrading?

**Comment by mircealungu** [comment]
Ehi @jakeLester66  - do you have time to look into what's necessary for the upgrade and send a PR maybe? If not, I will see whether some of my students will try to look into it, but I just do not have time at the moment :(

**Comment by HrisyToteva** [comment]
Hi @mat-l and @jakeLester66, thank you for bringing up this issue and taking the time to contribute to the Flask-MonitoringDashboard project.

As part of my school project, my team is conducting a usability research study to improve the dashboard. I noticed your experience with the app and thought it would be valuable to gather more insights from you.

Would you be open to receiving a few questions about your experience with Flask-MonitoringDashboard? It won't take more than 20 minutes to answer them. Your feedback will play a vital role in enhancing the app's functionality and addressing any existing limitations.

If you're interested, please let me know, and I will send you the questions. Your involvement would be highly valuable and greatly appreciated.

**Comment by mat-l** [comment]
Hi @HrisyToteva,
I was working with flask monitoring dashboard online a few weeks, until it stopped working because of missing Python support for Python 3.9, 3.10 and so on. Therefore I do not have any detailed user experience yet, because of that I cannot share any insights with you.
All the best for your project

**Comment by leetanshaj** [comment]
anything here??

**Comment by mircealungu** [comment]
this is fixed in the latest version. closing this issue.
