### ISSUE TITLE
Profiler does not add status code of request

### ISSUE THREAD

**Issue by bogdanp05** [flask-dashboard/Flask-MonitoringDashboard#241]
**Describe the bug**
Monitoring levels 2 and 3 cause the error: `No commit has been made, due to the following error: add_request() missing 1 required positional argument: 'status_code'`

**To Reproduce**
1. Set endpoint to monitoring level 2 or 3.
2. Call it.
3. See error.

**Expected behavior**
The profiler should add the request and the profiled info to the db.

**Screenshots**
N/A

**Environment:**
 - FMD Version 2.1.5. (development branch)

**Additional context**
Caused by PR #237

**Comment by bogdanp05** [comment]
@thejager can you fix this?

**Comment by thejager** [comment]
Should be fixed now in https://github.com/flask-dashboard/Flask-MonitoringDashboard/pull/248
